[package]
name = "rust"
version = "0.1.0"
edition = "2023"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bpf-sys = "2.3.0"
rebpf = "0.1.5"
